apiVersion: v1
data:
  pelican.logrotate: |
    /var/log/pelican/*.log {
        compress
        copytruncate
        size 500M
        missingok
        notifempty
        rotate 10
    }
kind: ConfigMap
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-cache-log-rotate-6f7f6k52k7
---
apiVersion: v1
data:
  pelican.yaml: |
    ---
    ConfigLocations:
      - "/usr/share/pelican/config.d"
      - "/etc/pelican/config.d"

    IssuerKey: "/etc/pelican/jwks/issuer.jwk"

    Cache:
      DataLocation: "/cache"
      Port: 8443

    Server:
      WebPort: 443
      TlsCertificate: "/etc/pelican/cert-orig/tls.crt"
      TlsKey: "/etc/pelican/cert-orig/tls.key"

    Logging:
      LogLocation: "/var/log/pelican/pelican.log"
      Level: "INFO"
kind: ConfigMap
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-default-config-47mk22297t
---
apiVersion: v1
data:
  50-instance.yaml: |
    ---

    Federation:
      #DiscoveryUrl: https://uwdf-director.chtc.wisc.edu
      DiscoveryUrl: https://chtc.wisc.edu

    Logging:
      LogLocation: /var/log/pelican/pelican.log
      Cache:
        Scitokens: trace

    Server:
      Hostname: uwdf-pelican-cache.uwdf-prod.chtc.io
      IssuerUrl: https://chtc.cs.wisc.edu

    Xrootd:
      # Topology Resource Name
      Sitename: CHTC-UWDF-cache

    Cache:
      StorageLocation: /cache
kind: ConfigMap
metadata:
  labels:
    instance: uwdf-osdf-pelican-cache
  name: uwdf-instance-config-h75hfc59m4
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: uwdf-pelican-cache.uwdf-prod.chtc.io
    metallb.universe.tf/address-pool: tiger-vlan2
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache
spec:
  externalTrafficPolicy: Local
  ports:
  - name: pelican
    port: 8443
    protocol: TCP
    targetPort: pelican
  - name: pelican-cvmfs
    port: 8000
    protocol: TCP
    targetPort: pelican-cvmfs
  - name: pelican-webui
    port: 443
    protocol: TCP
    targetPort: pelican-webui
  selector:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: 3x-replica-nvme-raddus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache-logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: 3x-replica-nvme-raddus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache-namespace-key
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: 3x-replica-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelican-cache
      instance: uwdf-osdf-pelican-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pelican-cache
        instance: uwdf-osdf-pelican-cache
    spec:
      containers:
      - args: []
        image: hub.opensciencegrid.org/pelican_platform/cache:v7.16.5
        imagePullPolicy: Always
        name: pelican-cache
        ports:
        - containerPort: 8443
          name: pelican
          protocol: TCP
        - containerPort: 443
          name: pelican-webui
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 16Gi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - mountPath: /etc/pelican/server-web-passwd
          name: webserver-passwd
          readOnly: true
          subPath: server-web-passwd
        - mountPath: /usr/share/pelican/config.d
          name: overlay-config
        - mountPath: /etc/pelican/pelican.yaml
          name: default-config
          subPath: pelican.yaml
        - mountPath: /etc/pelican/config.d
          name: instance-config
        - mountPath: /cache
          name: cache-data
        - mountPath: /var/log/pelican
          name: logging-volume
        - mountPath: /etc/pelican/jwks
          name: namespace-key
        - mountPath: /etc/pelican/cert-orig
          name: pelican-cache-ssl-cert
      - image: hub.opensciencegrid.org/pelican_platform/port-redirector:latest
        imagePullPolicy: Always
        name: cvmfs-redirector
        ports:
        - containerPort: 8000
          name: pelican-cvmfs
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
      - image: hub.opensciencegrid.org/opensciencegrid/logrotate:24-release
        name: logrotate
        resources:
          limits:
            cpu: "2"
            memory: 2G
          requests:
            cpu: "1"
            memory: 500M
        volumeMounts:
        - mountPath: /var/log/pelican
          name: logging-volume
        - mountPath: /etc/logrotate.d/
          name: log-rotate-config
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: tiger2003.chtc.wisc.edu
      volumes:
      - name: webserver-passwd
        secret:
          items:
          - key: webserver-passwd
            mode: 420
            path: server-web-passwd
          secretName: uwdf-pelican-webserver-passwd
      - emptyDir: {}
        name: overlay-config
      - name: pelican-cache-ssl-cert
        secret:
          items:
          - key: tls.crt
            mode: 420
            path: tls.crt
          - key: tls.key
            mode: 384
            path: tls.key
          secretName: uwdf-pelican-cache-cert
      - configMap:
          items:
          - key: pelican.yaml
            mode: 420
            path: pelican.yaml
          name: uwdf-default-config-47mk22297t
        name: default-config
      - configMap:
          name: uwdf-instance-config-h75hfc59m4
        name: instance-config
      - name: cache-data
        persistentVolumeClaim:
          claimName: uwdf-pelican-cache-data
      - name: logging-volume
        persistentVolumeClaim:
          claimName: uwdf-pelican-cache-logging
      - name: namespace-key
        persistentVolumeClaim:
          claimName: uwdf-pelican-cache-namespace-key
      - configMap:
          name: uwdf-cache-log-rotate-6f7f6k52k7
        name: log-rotate-config
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache-cert
spec:
  dnsNames:
  - uwdf-pelican-cache.uwdf-prod.chtc.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: uwdf-pelican-cache-cert
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: pelican-cache
    instance: uwdf-osdf-pelican-cache
  name: uwdf-pelican-cache
spec:
  egress:
  - {}
  ingress:
  - from: null
    ports:
    - port: 8443
      protocol: TCP
    - port: 8000
      protocol: TCP
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      app: pelican-cache
      instance: uwdf-osdf-pelican-cache
  policyTypes:
  - Ingress
  - Egress
