---
{{ if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "osdf-pelican-cache.fullname" . }}
spec:
  secretName: {{ template "osdf-pelican-cache.fullname" . }}-cert
  dnsNames:
  - {{ .Values.topologyFQDN }}
  issuerRef:
    name: {{ .Values.certmanager.issuerName }}
    kind: ClusterIssuer
{{ end }}
