apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-pelican-cache.fullname" . }}
  labels:
    {{- include "osdf-pelican-cache.labels" . | nindent 4 }}
data:
  pelican.yaml: |
    Federation:
      DirectorURL: {{ .Values.directorURL }}
      DiscoveryURL: {{ .Values.discoveryURL }}
    Server:
      Hostname: {{ .Values.topologyFQDN }}
      Webport: 443
      EnableUI: {{ .Values.webserver.enabled }}
      TLSCertificate: /etc/pelican/cert-orig/tls.crt
      TLSKey: /etc/pelican/cert-orig/tls.key
    Logging:
      Cache:
        Ofs: {{ .Values.logging.ofs }}
        Pfc: {{ .Values.logging.pfc }}
        Pss: {{ .Values.logging.pss }}
        Scitokens: {{ .Values.logging.scitokens }}
        Xrd: {{ .Values.logging.xrd }}
        Xrootd: {{ .Values.logging.xrootd }}
      Level: {{ .Values.logging.loglevel }}
    Shoveler:
      Enable: {{ .Values.monitoringShoveler.enabled }}
    XRootD:
      SciTokensConfig: /etc/pelican/topology/scitokens.cfg
    Cache:
      {{- with .Values.concurrency }}
      Concurrency: {{ . }}
      {{- end }}
      DataLocation: /cache
      Port: 8443
      SelfTest: {{ .Values.selfTest.enabled }}
      SelfTestInterval: {{ .Values.selfTest.interval }}
    {{- with .Values.extraPelicanConfig }}
{{- . | nindent 4 }}
    {{- end }}

