apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ template "osdf-origin.fullname" . }}
data:
  osdf-cache.yaml: |
    Federation:
      DirectorURL: {{ .Values.directorURL }}
      DiscoveryURL: {{ .Values.discoveryURL }}
    Server:
      Hostname: {{ topologyFQDN }}
      Webport: 443
      EnableUI: true
      TLSCertificate: /etc/pelican/cert-orig/tls.crt
      TLSKey: /etc/pelican/cert-orig/tls.key
    Logging:
      Cache:
        Scitokens: {{ .Values.logging.scitokens }}
        PSS: {{ .Values.logging.pss }}
      Level: {{ .Values.logging.loglevel }}
      LogLocation: /var/log/pelican/pelican.log
    Shoveler:
      Enable: false
    XRootD:
      SciTokensConfig: /etc/pelican/topology/scitokens.cfg
    Cache:
      DataLocation: /cache
      Port: 8443
    {{ if .Values.extraConfig }}
{{ .Values.extraConfig | indent 4 }}
    {{- end }}

