apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osdf-pelican-cache.fullname" . }}
  labels:
    app: {{ template "osdf-pelican-cache.name" . }}
    federation: osdf
    instance: {{ template "osdf-pelican-cache.fullname" . }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osdf-pelican-cache.name" . }}
      release: {{ .Release.Name }}
      instance: {{ template "osdf-pelican-cache.fullname" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "osdf-pelican-cache.name" . }}
        federation: osdf
        instance: {{ template "osdf-pelican-cache.fullname" . }}
        release: {{ .Release.Name }}

    spec:
      {{- if .Values.nodeName }}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      # securityContext:
      #   fsGroup: 10940
      # ^^ XXX do we need this?
      enableServiceLinks: false
      volumes:
        - name: topology-scitokens.cfg
          emptyDir: {}
        - name: webserver-passwd
          secret:
            items:
            - key: webserver-passwd
              mode: "0644"
              path: server-web-passwd
          secretName: {{ .Values.webPasswordSecret }}

        {{- if .Values.cacheVolumeClaimName }}
        - name: cache-data
          persistentVolumeClaim:
            claimName: {{ .cacheVolumeClaimName }}
        {{- end }}

        {{- if or .Values.certmanager.enabled .Values.hostCertKeySecret }}
        - name: hostcertkey
          secret:
            {{- if .Values.certmanager.enabled }}
            secretName: {{ template "osdf-pelican-cache.fullname" . }}-cert
            {{- else if .Values.hostCertKeySecret }}
            secretName: {{ .Values.hostCertKeySecret }}
            {{- end }}
            items:
            - key: tls.crt
              mode: 0o644
              path: tls.crt
            - key: tls.key
              mode: 0o400
              path: tls.key
        {{- end }}

        - name: config
          configMap:
            name: {{ template "osdf-pelican-cache.fullname" . }}

        {{- if .Values.logging.volumeClaimName }}
        - name: logging-volume
          persistentVolumeClaim:
            claimName: {{ .Values.logging.volumeClaimName }}
        {{- end }}

      # end volumes

      initContainers:
      - args:
        - -o
        - scitokens.cfg
        - --output-dir
        - /topology
        - {{ cat "https://topology.opensciencegrid.org/cache/scitokens.conf?fqdn="  .Values.topologyFQDN }}
        image: curlimages/curl:7.77.0
        name: topology-scitokens-fetcher
        volumeMounts:
        - mountPath: /topology
          name: topology-scitokens-cfg

      containers:
        - name: pelican-cache
          image: "{{ .Values.image.registry }}/{{ .Values.image.organization }}/osdf-cache:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.extraEnv }}
          env:
              {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbeEnabled }}
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 600
            periodSeconds: 60
          {{- end }}
          ports:
            - containerPort: 8443
              name: pelican
              protocol: TCP
            - containerPort: 443
              name: pelican-webui
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/pelican/server-web-passwd
              name: webserver-passwd
              readOnly: true
              subPath: server-web-passwd
            - mountPath: /etc/pelican/topology
              name: topology-scitokens-cfg
            - mountPath: /cache
              name: cache-data
            {{- if or .Values.certmanager.enabled .Values.hostCertKeySecret }}
            - mountPath: /etc/pelican/cert-orig
              name: pelican-cache-ssl-cert
            {{ end }}
            {{- if .Values.logging.volumeClaimName }}
            - mountPath: /var/log/pelican
              name: logging-volume
            {{ end }}
          # end volumeMounts
      # end containers
    # end spec
  # end template
# end spec

# vim:et:sw=2:sts=2:ts=8
