apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "osdf-pelican-cache.fullname" . }}
  labels:
    {{- include "osdf-pelican-cache.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "osdf-pelican-cache.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 443
  egress:
    - {}
