apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "osdf-origin.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "osdf-origin.name" . }}
      release: {{ .Release.Name }}
      instance: {{ template "osdf-origin.fullname" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 443
  egress:
    - {}
