{{- if not .Values.cacheVolume.useExisting }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "osdf-pelican-cache.labels" . | nindent 4 }}
  name: {{ template "osdf-pelican-cache.cachepvcname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheVolume.storage }}
  storageClassName: {{ .Values.cacheVolume.storageClassName }}
{{- end }}
