{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "osdf-pelican-cache.fullname" . }}
  labels:
    {{- include "osdf-pelican-cache.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.topologyFQDN | quote }}
    {{- with .Values.serviceAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: pelican
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: pelican-webui
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    {{- include "osdf-pelican-cache.selectorLabels" . | nindent 4 }}
{{- end }}
