# Default values for pelican-cache.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

federation:
  name: osdf
  discoveryUrl: https://osg-htc.org

# Sets the hostname to advertise to the director with, and use for external-dns
hostname: cache.example.net
issuerUrl: ""
xrootdSitename: ""

cache:
  volume: ""

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: hub.opensciencegrid.org/pelican_platform/cache
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

logging:
  level: info
  sublevels: {}
    # Scitokens: trace
  persistence:
    enabled: true
    volume: ""

# These are the names of Secrets
secrets:
  # This should have a single "issuer.pem"
  issuerKey: ""
  # The SSL/TLS certificate and key (tls.crt, tls.key)
  sslCertificate: ""
  # The admin password for the webserver
  webserverPassword: ""

# To persist monitoring information, you must have a volume for it; the recommended size is 20 GiB
monitoringVolume: ""

# To persist the namespace key, you must have a volume for it
namespaceKeyVolume: ""


podAnnotations: {}
podLabels: {}

securityContext: {}
  # capabilities:
  #   add:
  #   - SYS_PTRACE

service:
  enabled: true
  # Annotations, such as metallb.universe.tf/address-pool
  annotations: {}

cvmfsCompatEnabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Turn this on to sleep forever instead of running the cache, for debugging
sleepForever: false

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
