---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pelican-cache.fullname" . }}-logrotate
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
data:
  pelican.logrotate: |
    /var/log/pelican/*.log {
        compress
        copytruncate
        size 500M
        missingok
        notifempty
        rotate 10
    }

