---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pelican-cache.fullname" . }}
  labels:
    {{- include "pelican-cache.labels" . | nindent 4 }}
spec:
  egress:
  - {}
  ingress:
  - from: null
    ports:
    - port: 8443
      protocol: TCP
    {{- if .Values.cvmfsCompatEnabled }}
    - port: 8000
      protocol: TCP
    {{- end }}
    - port: 443
      protocol: TCP
  podSelector:
    matchLabels:
      {{- include "pelican-cache.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
