apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-hosted-ce.fullname" . }}
  labels:
    app: {{ template "osg-hosted-ce.name" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-hosted-ce.name" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: {{ template "osg-hosted-ce.name" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      {{ if .Values.NodeSelection.Enabled }}
      nodeSelector: 
        {{ if .Values.NodeSelection.NodeLabels}}
        {{- range $key, $value := .Values.NodeSelection.NodeLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{ end }}
      {{ end }}
      volumes:
      {{ if .Values.Persistence.IdtokenKeyVolume }}
      - name: idtoken-key-condor-ce
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.IdtokenKeyVolume }}
      {{ end }}
      {{ if .Values.Persistence.LibCondorCeVolume }}
      - name: lib-condor-ce
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.LibCondorCeVolume }}
      {{ end }}
      {{ if .Values.ExternalHTCondorCeConfig }}
      {{- range .Values.ExternalHTCondorCeConfig }}
      - name: {{ .Name }}
        configMap:
          name: {{ .Name }}
      {{- end }}
      {{ end }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-configuration
      - name: osg-hosted-ce-{{ .Values.Instance }}-htcondor-ce-configuration
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-htcondor-ce-configuration
      - name: osg-hosted-ce-{{ .Values.Instance }}-scitokens
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-scitokens
      - name: bosco-ssh-private-key-volume
        secret: 
          secretName: {{ .Values.RemoteCluster.PrivateKeySecret }}
          items:
          - key: bosco.key
            path: bosco.key
            mode: 256
      {{ if .Values.RemoteCluster.SSHCertificateSecret }}
      - name: bosco-ssh-cert-volume
        secret:
          secretName: {{ .Values.RemoteCluster.SSHCertificateSecret }}
          items:
          - key: bosco.cert
            path: bosco.cert
            mode: 0o400
      {{ end }}
      {{ if .Values.RemoteCluster.KnownHosts }}
      - name: ssh-known-hosts
        configMap:
          name: osg-hosted-ce-{{ .Values.Instance }}-known-hosts
      {{ end }}
      {{ if .Values.HostCredentials.HostCertKeySecret }}
      - name: osg-hosted-ce-hostcertkey-volume
        secret:
          secretName: {{ .Values.HostCredentials.HostCertKeySecret }}
          items:
          - key: tls.crt
            path: hostcert.pem
            mode: 0o644
          - key: tls.key
            path: hostkey.pem
            mode: 0o400
      {{ end }}
      {{ if .Values.BoscoOverrides.Enabled }}
      {{ if .Values.BoscoOverrides.GitKeySecret }}
      - name: osg-hosted-ce-{{ .Values.Instance }}-gitkey
        secret:
          secretName: {{ .Values.BoscoOverrides.GitKeySecret }}
          items:
          - key: git.key
            path: git.key
            mode: 256 
      {{ end }}
      {{ end }}
      {{ if .Values.Persistence.LogVolume }}
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.Persistence.LogVolume }}
      {{ end }}
      {{ if eq .Values.Networking.ServiceType "HostNetwork" }}
      hostNetwork: true
      {{ end }}
      containers:
      - name: osg-hosted-ce
        {{ if .Values.ContainerTags.HostedCE | default "" | contains "23-" }}
        image: hub.opensciencegrid.org/opensciencegrid/hosted-ce:{{ .Values.ContainerTags.HostedCE }}
        {{ else }}
        image: hub.opensciencegrid.org/osg-htc/hosted-ce:{{ .Values.ContainerTags.HostedCE }}
        {{ end }}
        imagePullPolicy: Always
        volumeMounts:
        - name: osg-hosted-ce-{{ .Values.Instance }}-configuration
          mountPath: /tmp/etc/osg/config.d
        {{ if .Values.ExternalHTCondorCeConfig }}
        {{- range .Values.ExternalHTCondorCeConfig }}
        - name: {{ .Name }}
          mountPath: {{ .Directory | default "/etc/condor-ce/config.d" }}/{{ .File }}
          subPath: {{ .File }}
        {{- end}}
        {{ end }}
        - name: bosco-ssh-private-key-volume
          mountPath: /etc/osg/bosco.key
          subPath: bosco.key
        {{ if .Values.RemoteCluster.SSHCertificateSecret }}
        - name: bosco-ssh-cert-volume
          mountPath: /etc/osg/bosco.key-cert.pub
          subPath: bosco.cert
        {{ end }}
        {{ if .Values.RemoteCluster.KnownHosts }}
        - name: ssh-known-hosts
          mountPath: /etc/osg/ssh_known_hosts
          subPath: ssh_known_hosts
        {{ end }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-htcondor-ce-configuration
          mountPath: /etc/condor-ce/config.d/90-instance.conf
          subPath: 90-instance.conf
        {{ if .Values.Persistence.IdtokenKeyVolume }}
        - name: idtoken-key-condor-ce
          mountPath: /etc/condor-ce/passwords.d/
        {{ end }}
        {{ if .Values.Persistence.LibCondorCeVolume }}
        - name: lib-condor-ce
          mountPath: /var/lib/condor-ce
        {{ end }}
        {{ if .Values.HostCredentials.HostCertKeySecret }}
        - name: osg-hosted-ce-hostcertkey-volume
          mountPath: /etc/grid-security-orig.d
        {{ end }}
        {{ if .Values.Persistence.LogVolume}}
        - name: log-volume
          mountPath: /var/log/condor-ce
        {{ end }}
        {{ if .Values.BoscoOverrides.Enabled }}
        {{ if .Values.BoscoOverrides.GitKeySecret }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-gitkey
          mountPath: /etc/osg/git.key
          subPath: git.key
        {{ end }}
        {{ end }}
        {{ if .Values.SciTokenRemoteUserMapping }}
        - name: osg-hosted-ce-{{ .Values.Instance }}-scitokens
          mountPath: /etc/condor-ce/mapfiles.d/50-scitokens.conf
          subPath: 50-scitokens.conf
        {{ end }}
        ports:
        - name: htcondor-ce
          containerPort: 9619
          protocol: TCP
        env:
        {{ if eq .Values.Networking.ServiceType "HostNetwork" }}
        - name: _CONDOR_NETWORK_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{ else if eq .Values.Networking.ServiceType "LoadBalancer" }} 
        - name: _CONDOR_NETWORK_HOSTNAME
          value: {{ .Values.Networking.Hostname }}
        - name: CE_HOSTNAME
          value: {{ .Values.Networking.Hostname }}
        {{ end }}
        - name: CE_CONTACT
          value: {{ .Values.Topology.ContactEmail }}
        - name: LE_STAGING
          {{ if .Values.HostCredentials.LetsEncryptStaging }} # https://github.com/helm/helm/issues/2848
          value: "true"
          {{ else }}
          value: "false"
          {{ end }}
        {{ if .Values.Debug.ContinueOnError }}
        - name: HOSTED_CE_CONTINUE_ON_ERROR
          value: "true"
        {{ end }}
        - name: RESOURCE_NAME
          value: {{ .Values.Topology.Resource }}
        - name: REMOTE_HOST
          value: {{ .Values.RemoteCluster.LoginHost }}
        {{ if .Values.RemoteCluster.ProxyJump }}
        - name: SSH_PROXY_JUMP
          value: {{ .Values.RemoteCluster.ProxyJump }}
        {{ end }}
        {{ if .Values.RemoteCluster.ProxyJumpUser }}
        - name: SSH_PROXY_JUMP_USER
          value: {{ .Values.RemoteCluster.ProxyJumpUser }}
        {{ end }}
        - name: REMOTE_BATCH
          value: {{ .Values.RemoteCluster.Batch | lower }}
        - name: REMOTE_BOSCO_DIR
          value: {{ .Values.RemoteCluster.BoscoDir | default "bosco" }}
        {{ if .Values.BoscoOverrides.TarballURL }}
        - name: BOSCO_TARBALL_URL
          value: {{ .Values.BoscoOverrides.TarballURL }}
        {{ end }}
        - name: DEVELOPER
          {{ if .Values.Developer.Enabled }}  # https://github.com/helm/helm/issues/2848
          value: "true"
          {{ else }}
          value: "false"
          {{ end }}
        {{ if .Values.BoscoOverrides.Enabled }}
        - name: BOSCO_GIT_ENDPOINT
          value: {{ .Values.BoscoOverrides.GitEndpoint }}
        - name: BOSCO_DIRECTORY
          value: {{ .Values.BoscoOverrides.BoscoOverrideDir | default .Values.Topology.Resource }}
        {{ end }}
        {{  if not .Values.Persistence.LibCondorCeVolume }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/local/bin/drain-ce.sh"]
        {{ end }}
